import type { NextPage } from "next";
import Head from "next/head";
import DownloadPage from "./download-page";
import LandingPage from "./landing-page";
import LandingPage1 from "./landing-page1";
import { useRecoilValue } from "recoil";
import { pageRecoil } from "../recoil/page";

const Home: NextPage = () => {
  const page = useRecoilValue(pageRecoil);
  // const onWindowWheel = (event: React.WheelEvent<HTMLDivElement>) => {
  //   const y = event.deltaY;
  //   if (y > 0) {
  //     setPage(2);
  //   } else {
  //     setPage(1);
  //   }
  // };

  return (
    <div>
      <Head>
        <title>Halome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="absolute">
        {
          page == 1
            ?
            <LandingPage />
            :
            page == 2
              ?
              <LandingPage1 />
              :
              null
        }
      </main>
    </div>
  );
};

export default Home;
